Upgrade to Poetry 1.2.0 (#39)

diff --git a/run b/run
--- a/run
+++ b/run
@@ -4,8 +4,15 @@
 # Setup the virtual environment via Poetry and install pre-commit hooks
 run_install() {
 
-   # Create and update the virtualenv
-   poetry install -v
+   # Install the poetry-plugin-export plugin, used to generate requirements.txt
+   PYTHON_KEYRING_BACKEND="keyring.backends.null.Keyring" poetry self add --quiet poetry-plugin-export
+   if [ $? != 0 ]; then
+      echo "Failed to install Poetry plugin: poetry-plugin-export"
+      exit 1
+   fi
+
+   # Create and update the virtualenv, synchronizing it to versions in poetry.lock
+   poetry install --quiet --sync
    if [ $? != 0 ]; then
       exit 1
    fi
@@ -29,7 +36,7 @@ run_activate() {
 
 # Regenerate the docs/requirements.txt file"
 run_requirements() {
-   poetry export --format=requirements.txt --without-hashes --dev --output=docs/requirements.txt
+   poetry export --format=requirements.txt --without-hashes --with dev --output=docs/requirements.txt
    if [ $? != 0 ]; then
       exit 1
    fi
@@ -199,6 +206,7 @@ run_docs() {
 
 # Release a specific version and tag the code
 run_release() {
+
    if [ $# != 1 ]; then
       echo "run release <version>"
       exit 1
